name: Deploy to CentOS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to CentOS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ 22 }}
        script: |
          cd /root/test/deploy
          git pull origin master
          dotnet publish -c Release -r linux-x64
          # Additional deployment steps, e.g., restart the application, etc.
