name: Deploy to CentOS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Build and Publish
      run: dotnet publish -c Release -r -linux-x64

    - name: Deploy to CentOS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ 47.100.170.34 }}
        username: ${{ root }}
        key: ${{ Laojiegao521@ }}
        port: ${{ 22 }}
        script: |
          cd /root/test/deploy
          scp -r $GITHUB_WORKSPACE/publish/* .
          # Additional deployment steps, e.g., restart the application, etc.
