name: ASP.NET Core Deployment

on:
  push:
    branches:
      - master  # 你可以根据需要更改分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1'  # 你可以根据需要更改 .NET Core 版本

    - name: Build and Publish
      run: |
        dotnet publish -c Release -r linux-x64 -o out

    - name: Copy Files to Server
      uses: appleboy/scp-action@master
      with:
        host:  ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: 22
        source: "out/"
        target: "/root/test/deploy"

    - name: SSH into Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: 22
        script: whoami
          # 在这里执行停止应用、备份数据等操作
          # 例如：sudo systemctl stop your-app.service
